services:
    _defaults:
        autowire: true
        autoconfigure: true

    SoftWax\CorrelationIds\:
        resource: '../../*'
        exclude:
            - '../../SoftWaxCorrelationIdsBundle.php'
            - '../../DependencyInjection'
            - '../../Model'
            - '../../Resources'
